<?php

use Illuminate\Database\Seeder;

class PatternSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('patterns')->delete();

        $patterns = [
            ['id'=>1,'brand_id'=>1,'name'=>'STX'],
            ['id'=>2,'brand_id'=>1,'name'=>'Otro Modelo'],
            ['id'=>3,'brand_id'=>2,'name'=>'500'],
            ['id'=>4,'brand_id'=>2,'name'=>'600'],
            ['id'=>5,'brand_id'=>2,'name'=>'Otro Modelo'],
            ['id'=>6,'brand_id'=>3,'name'=>'Andina'],
            ['id'=>7,'brand_id'=>3,'name'=>'Beraka'],
            ['id'=>8,'brand_id'=>3,'name'=>'Bless'],
            ['id'=>9,'brand_id'=>3,'name'=>'Brezza'],
            ['id'=>10,'brand_id'=>3,'name'=>'Citi Plus'],
            ['id'=>11,'brand_id'=>3,'name'=>'DCN'],
            ['id'=>12,'brand_id'=>3,'name'=>'Geremy'],
            ['id'=>13,'brand_id'=>3,'name'=>'Hardwind'],
            ['id'=>14,'brand_id'=>3,'name'=>'Leyenda'],
            ['id'=>15,'brand_id'=>3,'name'=>'Montero'],
            ['id'=>16,'brand_id'=>3,'name'=>'Regia'],
            ['id'=>17,'brand_id'=>3,'name'=>'Stronger'],
            ['id'=>18,'brand_id'=>3,'name'=>'Vectra'],
            ['id'=>19,'brand_id'=>3,'name'=>'Otro Modelo'],
            ['id'=>20,'brand_id'=>4,'name'=>'RS'],
            ['id'=>21,'brand_id'=>4,'name'=>'STX'],
            ['id'=>22,'brand_id'=>4,'name'=>'Otro Modelo'],
            ['id'=>23,'brand_id'=>5,'name'=>'Avenger'],
            ['id'=>24,'brand_id'=>5,'name'=>'Discover'],
            ['id'=>25,'brand_id'=>5,'name'=>'Dominar'],
            ['id'=>26,'brand_id'=>5,'name'=>'Pulsar'],
            ['id'=>27,'brand_id'=>5,'name'=>'Rouser'],
            ['id'=>28,'brand_id'=>5,'name'=>'XCD'],
            ['id'=>29,'brand_id'=>5,'name'=>'Otro Modelo'],
            ['id'=>30,'brand_id'=>6,'name'=>'302'],
            ['id'=>31,'brand_id'=>6,'name'=>'Leoncino'],
            ['id'=>32,'brand_id'=>6,'name'=>'TNT'],
            ['id'=>33,'brand_id'=>6,'name'=>'TRK'],
            ['id'=>34,'brand_id'=>6,'name'=>'Otro Modelo'],
            ['id'=>35,'brand_id'=>7,'name'=>'Arrow'],
            ['id'=>36,'brand_id'=>7,'name'=>'BK'],
            ['id'=>37,'brand_id'=>7,'name'=>'Boy'],
            ['id'=>38,'brand_id'=>7,'name'=>'BS'],
            ['id'=>39,'brand_id'=>7,'name'=>'Chrono'],
            ['id'=>40,'brand_id'=>7,'name'=>'Euro'],
            ['id'=>41,'brand_id'=>7,'name'=>'Kinder'],
            ['id'=>42,'brand_id'=>7,'name'=>'Lem'],
            ['id'=>43,'brand_id'=>7,'name'=>'Motard'],
            ['id'=>44,'brand_id'=>7,'name'=>'Neos'],
            ['id'=>45,'brand_id'=>7,'name'=>'Pro Race'],
            ['id'=>46,'brand_id'=>7,'name'=>'RR'],
            ['id'=>47,'brand_id'=>7,'name'=>'Scooby'],
            ['id'=>48,'brand_id'=>7,'name'=>'TR'],
            ['id'=>49,'brand_id'=>7,'name'=>'Urba'],
            ['id'=>50,'brand_id'=>7,'name'=>'Otro Modelo'],
            ['id'=>51,'brand_id'=>8,'name'=>'Ferrari'],
            ['id'=>52,'brand_id'=>8,'name'=>'Otro Modelo'],
            ['id'=>53,'brand_id'=>9,'name'=>'60/6'],
            ['id'=>54,'brand_id'=>9,'name'=>'60/7'],
            ['id'=>55,'brand_id'=>9,'name'=>'Ferrari'],
            ['id'=>56,'brand_id'=>9,'name'=>'Geremy'],
            ['id'=>57,'brand_id'=>9,'name'=>'GS'],
            ['id'=>58,'brand_id'=>9,'name'=>'K'],
            ['id'=>59,'brand_id'=>9,'name'=>'Nine T'],
            ['id'=>60,'brand_id'=>9,'name'=>'R'],
            ['id'=>61,'brand_id'=>9,'name'=>'RR'],
            ['id'=>62,'brand_id'=>9,'name'=>'RT'],
            ['id'=>63,'brand_id'=>9,'name'=>'S'],
            ['id'=>64,'brand_id'=>9,'name'=>'Scooter'],
            ['id'=>65,'brand_id'=>9,'name'=>'Otro Modelo'],
            ['id'=>66,'brand_id'=>10,'name'=>'Alpina'],
            ['id'=>67,'brand_id'=>10,'name'=>'Altino'],
            ['id'=>68,'brand_id'=>10,'name'=>'Apolo'],
            ['id'=>69,'brand_id'=>10,'name'=>'Aquila'],
            ['id'=>70,'brand_id'=>10,'name'=>'Athene'],
            ['id'=>71,'brand_id'=>10,'name'=>'Daystar'],
            ['id'=>72,'brand_id'=>10,'name'=>'Elektra'],
            ['id'=>73,'brand_id'=>10,'name'=>'Nevada'],
            ['id'=>74,'brand_id'=>10,'name'=>'Texana HS'],
            ['id'=>75,'brand_id'=>10,'name'=>'Winstar'],
            ['id'=>76,'brand_id'=>10,'name'=>'Otro Modelo'],
            ['id'=>77,'brand_id'=>11,'name'=>'Elefant'],
            ['id'=>78,'brand_id'=>11,'name'=>'Gran Canyon'],
            ['id'=>79,'brand_id'=>11,'name'=>'Planet'],
            ['id'=>80,'brand_id'=>11,'name'=>'Roadster'],
            ['id'=>81,'brand_id'=>11,'name'=>'Otro Modelo'],
            ['id'=>82,'brand_id'=>12,'name'=>'CE'],
            ['id'=>83,'brand_id'=>12,'name'=>'XRC'],
            ['id'=>84,'brand_id'=>12,'name'=>'Otro Modelo'],
            ['id'=>85,'brand_id'=>13,'name'=>'DX'],
            ['id'=>86,'brand_id'=>13,'name'=>'Energy'],
            ['id'=>87,'brand_id'=>13,'name'=>'Expert'],
            ['id'=>88,'brand_id'=>13,'name'=>'Hunter'],
            ['id'=>89,'brand_id'=>13,'name'=>'Indiana'],
            ['id'=>90,'brand_id'=>13,'name'=>'Mirage'],
            ['id'=>91,'brand_id'=>13,'name'=>'Triax'],
            ['id'=>92,'brand_id'=>13,'name'=>'Otro Modelo'],
            ['id'=>93,'brand_id'=>14,'name'=>'E250'],
            ['id'=>94,'brand_id'=>14,'name'=>'LT'],
            ['id'=>95,'brand_id'=>14,'name'=>'Otro Modelo'],
            ['id'=>96,'brand_id'=>15,'name'=>'Cordi'],
            ['id'=>97,'brand_id'=>15,'name'=>'Daystar'],
            ['id'=>98,'brand_id'=>15,'name'=>'Delfino'],
            ['id'=>99,'brand_id'=>15,'name'=>'Liberty'],
            ['id'=>100,'brand_id'=>15,'name'=>'Magma'],
            ['id'=>101,'brand_id'=>15,'name'=>'Message'],
            ['id'=>102,'brand_id'=>15,'name'=>'Roadwin'],
            ['id'=>103,'brand_id'=>15,'name'=>'S1'],
            ['id'=>104,'brand_id'=>15,'name'=>'S-Five'],
            ['id'=>105,'brand_id'=>15,'name'=>'Otro Modelo'],
            ['id'=>106,'brand_id'=>16,'name'=>'100'],
            ['id'=>107,'brand_id'=>16,'name'=>'Otro Modelo'],
            ['id'=>108,'brand_id'=>17,'name'=>'RT'],
            ['id'=>109,'brand_id'=>17,'name'=>'Otro Modelo'],
            ['id'=>110,'brand_id'=>18,'name'=>'GT'],
            ['id'=>111,'brand_id'=>18,'name'=>'M'],
            ['id'=>112,'brand_id'=>18,'name'=>'Monster'],
            ['id'=>113,'brand_id'=>18,'name'=>'Multistrada'],
            ['id'=>114,'brand_id'=>18,'name'=>'Paul Smart'],
            ['id'=>115,'brand_id'=>18,'name'=>'S4R'],
            ['id'=>116,'brand_id'=>18,'name'=>'Sport Classic'],
            ['id'=>117,'brand_id'=>18,'name'=>'ST3'],
            ['id'=>118,'brand_id'=>18,'name'=>'ST4'],
            ['id'=>119,'brand_id'=>18,'name'=>'Super Sport'],
            ['id'=>120,'brand_id'=>18,'name'=>'Superbike'],
            ['id'=>121,'brand_id'=>18,'name'=>'Otro Modelo'],
            ['id'=>122,'brand_id'=>19,'name'=>'GXT'],
            ['id'=>123,'brand_id'=>19,'name'=>'HJ'],
            ['id'=>124,'brand_id'=>19,'name'=>'JM'],
            ['id'=>125,'brand_id'=>19,'name'=>'Otro Modelo'],
            ['id'=>126,'brand_id'=>20,'name'=>'Ego'],
            ['id'=>127,'brand_id'=>20,'name'=>'Otro Modelo'],
            ['id'=>128,'brand_id'=>21,'name'=>'98cc'],
            ['id'=>129,'brand_id'=>21,'name'=>'Otro Modelo'],
            ['id'=>130,'brand_id'=>22,'name'=>'Noi'],
            ['id'=>131,'brand_id'=>22,'name'=>'Otro Modelo'],
            ['id'=>132,'brand_id'=>23,'name'=>'EX'],
            ['id'=>133,'brand_id'=>23,'name'=>'Otro Modelo'],
            ['id'=>134,'brand_id'=>24,'name'=>'B'],
            ['id'=>135,'brand_id'=>24,'name'=>'C'],
            ['id'=>136,'brand_id'=>24,'name'=>'Estilo'],
            ['id'=>137,'brand_id'=>24,'name'=>'Futura'],
            ['id'=>138,'brand_id'=>24,'name'=>'FX'],
            ['id'=>139,'brand_id'=>24,'name'=>'G1'],
            ['id'=>140,'brand_id'=>24,'name'=>'GA'],
            ['id'=>141,'brand_id'=>24,'name'=>'Garelli'],
            ['id'=>142,'brand_id'=>24,'name'=>'GLA'],
            ['id'=>143,'brand_id'=>24,'name'=>'Gran Turismo'],
            ['id'=>144,'brand_id'=>24,'name'=>'Jazz'],
            ['id'=>145,'brand_id'=>24,'name'=>'Macho'],
            ['id'=>146,'brand_id'=>24,'name'=>'QAX'],
            ['id'=>147,'brand_id'=>24,'name'=>'QM'],
            ['id'=>148,'brand_id'=>24,'name'=>'Smash'],
            ['id'=>149,'brand_id'=>24,'name'=>'SMX'],
            ['id'=>150,'brand_id'=>24,'name'=>'Spring Country'],
            ['id'=>151,'brand_id'=>24,'name'=>'Súper Sport'],
            ['id'=>152,'brand_id'=>24,'name'=>'VC'],
            ['id'=>153,'brand_id'=>24,'name'=>'YL'],
            ['id'=>154,'brand_id'=>24,'name'=>'Otro Modelo'],
            ['id'=>155,'brand_id'=>25,'name'=>'Bike'],
            ['id'=>156,'brand_id'=>25,'name'=>'Day'],
            ['id'=>157,'brand_id'=>25,'name'=>'DL'],
            ['id'=>158,'brand_id'=>25,'name'=>'Econo'],
            ['id'=>159,'brand_id'=>25,'name'=>'Flash'],
            ['id'=>160,'brand_id'=>25,'name'=>'GC'],
            ['id'=>161,'brand_id'=>25,'name'=>'GMX'],
            ['id'=>162,'brand_id'=>25,'name'=>'GRF'],
            ['id'=>163,'brand_id'=>25,'name'=>'GRX'],
            ['id'=>164,'brand_id'=>25,'name'=>'GSL'],
            ['id'=>165,'brand_id'=>25,'name'=>'GVL'],
            ['id'=>166,'brand_id'=>25,'name'=>'GW'],
            ['id'=>167,'brand_id'=>25,'name'=>'GXL'],
            ['id'=>168,'brand_id'=>25,'name'=>'GXM'],
            ['id'=>169,'brand_id'=>25,'name'=>'Keoken'],
            ['id'=>170,'brand_id'=>25,'name'=>'On-off'],
            ['id'=>171,'brand_id'=>25,'name'=>'Trip'],
            ['id'=>172,'brand_id'=>25,'name'=>'Otro Modelo'],
            ['id'=>173,'brand_id'=>26,'name'=>'NTX'],
            ['id'=>174,'brand_id'=>26,'name'=>'Otro Modelo'],
            ['id'=>175,'brand_id'=>27,'name'=>'Buell'],
            ['id'=>176,'brand_id'=>27,'name'=>'Dynas'],
            ['id'=>177,'brand_id'=>27,'name'=>'Police'],
            ['id'=>178,'brand_id'=>27,'name'=>'Screaming Eagle'],
            ['id'=>179,'brand_id'=>27,'name'=>'Softails'],
            ['id'=>180,'brand_id'=>27,'name'=>'Sporters'],
            ['id'=>181,'brand_id'=>27,'name'=>'Tourings'],
            ['id'=>182,'brand_id'=>27,'name'=>'V-Rod'],
            ['id'=>183,'brand_id'=>27,'name'=>'Otro Modelo'],
            ['id'=>184,'brand_id'=>28,'name'=>'Africa Twin'],
            ['id'=>185,'brand_id'=>28,'name'=>'Ascot'],
            ['id'=>186,'brand_id'=>28,'name'=>'AX-1'],
            ['id'=>187,'brand_id'=>28,'name'=>'Biz'],
            ['id'=>188,'brand_id'=>28,'name'=>'C90'],
            ['id'=>189,'brand_id'=>28,'name'=>'CB'],
            ['id'=>190,'brand_id'=>28,'name'=>'CB1'],
            ['id'=>191,'brand_id'=>28,'name'=>'CBR'],
            ['id'=>192,'brand_id'=>28,'name'=>'CBX'],
            ['id'=>193,'brand_id'=>28,'name'=>'CG'],
            ['id'=>194,'brand_id'=>28,'name'=>'Corvex'],
            ['id'=>195,'brand_id'=>28,'name'=>'CR'],
            ['id'=>196,'brand_id'=>28,'name'=>'CRF'],
            ['id'=>197,'brand_id'=>28,'name'=>'CX'],
            ['id'=>198,'brand_id'=>28,'name'=>'Dax'],
            ['id'=>199,'brand_id'=>28,'name'=>'Deuville'],
            ['id'=>200,'brand_id'=>28,'name'=>'Dio'],
            ['id'=>201,'brand_id'=>28,'name'=>'Dominator'],
            ['id'=>202,'brand_id'=>28,'name'=>'Econo'],
            ['id'=>203,'brand_id'=>28,'name'=>'Elite'],
            ['id'=>204,'brand_id'=>28,'name'=>'Falcon'],
            ['id'=>205,'brand_id'=>28,'name'=>'GLH'],
            ['id'=>206,'brand_id'=>28,'name'=>'Goldwing'],
            ['id'=>207,'brand_id'=>28,'name'=>'Invicta'],
            ['id'=>208,'brand_id'=>28,'name'=>'Kinetic'],
            ['id'=>209,'brand_id'=>28,'name'=>'Lead'],
            ['id'=>210,'brand_id'=>28,'name'=>'Magna'],
            ['id'=>211,'brand_id'=>28,'name'=>'MB'],
            ['id'=>212,'brand_id'=>28,'name'=>'MTX'],
            ['id'=>213,'brand_id'=>28,'name'=>'NC'],
            ['id'=>214,'brand_id'=>28,'name'=>'Nighthawk'],
            ['id'=>215,'brand_id'=>28,'name'=>'NS'],
            ['id'=>216,'brand_id'=>28,'name'=>'NSR'],
            ['id'=>217,'brand_id'=>28,'name'=>'NX'],
            ['id'=>218,'brand_id'=>28,'name'=>'NXR'],
            ['id'=>219,'brand_id'=>28,'name'=>'Pacific Coast'],
            ['id'=>220,'brand_id'=>28,'name'=>'Pop'],
            ['id'=>221,'brand_id'=>28,'name'=>'Rebel'],
            ['id'=>222,'brand_id'=>28,'name'=>'Shadow'],
            ['id'=>223,'brand_id'=>28,'name'=>'ST'],
            ['id'=>224,'brand_id'=>28,'name'=>'Storm'],
            ['id'=>225,'brand_id'=>28,'name'=>'Titan'],
            ['id'=>226,'brand_id'=>28,'name'=>'Tornado'],
            ['id'=>227,'brand_id'=>28,'name'=>'Transalp'],
            ['id'=>228,'brand_id'=>28,'name'=>'Twinstar'],
            ['id'=>229,'brand_id'=>28,'name'=>'Varadero'],
            ['id'=>230,'brand_id'=>28,'name'=>'VFR'],
            ['id'=>231,'brand_id'=>28,'name'=>'VLX'],
            ['id'=>232,'brand_id'=>28,'name'=>'V-Men'],
            ['id'=>233,'brand_id'=>28,'name'=>'VTF'],
            ['id'=>234,'brand_id'=>28,'name'=>'VTX'],
            ['id'=>235,'brand_id'=>28,'name'=>'Wave'],
            ['id'=>236,'brand_id'=>28,'name'=>'XL'],
            ['id'=>237,'brand_id'=>28,'name'=>'XLR'],
            ['id'=>238,'brand_id'=>28,'name'=>'XR'],
            ['id'=>239,'brand_id'=>28,'name'=>'XRE'],
            ['id'=>240,'brand_id'=>28,'name'=>'Otro Modelo'],
            ['id'=>241,'brand_id'=>29,'name'=>'FE'],
            ['id'=>242,'brand_id'=>29,'name'=>'FX'],
            ['id'=>243,'brand_id'=>29,'name'=>'TE'],
            ['id'=>244,'brand_id'=>29,'name'=>'Otro Modelo'],
            ['id'=>245,'brand_id'=>30,'name'=>'CR'],
            ['id'=>246,'brand_id'=>30,'name'=>'Svartpilen'],
            ['id'=>247,'brand_id'=>30,'name'=>'TC'],
            ['id'=>248,'brand_id'=>30,'name'=>'TE'],
            ['id'=>249,'brand_id'=>30,'name'=>'Vitpilen'],
            ['id'=>250,'brand_id'=>30,'name'=>'WR'],
            ['id'=>251,'brand_id'=>30,'name'=>'Otro Modelo'],
            ['id'=>252,'brand_id'=>31,'name'=>'Road'],
            ['id'=>253,'brand_id'=>31,'name'=>'Trophy'],
            ['id'=>254,'brand_id'=>31,'name'=>'Otro Modelo'],
            ['id'=>255,'brand_id'=>32,'name'=>'150'],
            ['id'=>256,'brand_id'=>32,'name'=>'Otro Modelo'],
            ['id'=>257,'brand_id'=>33,'name'=>'Bobber'],
            ['id'=>258,'brand_id'=>33,'name'=>'Café Racer'],
            ['id'=>259,'brand_id'=>33,'name'=>'Daytona'],
            ['id'=>260,'brand_id'=>33,'name'=>'DD'],
            ['id'=>261,'brand_id'=>33,'name'=>'Ruta 40'],
            ['id'=>262,'brand_id'=>33,'name'=>'RVM'],
            ['id'=>263,'brand_id'=>33,'name'=>'Spyder'],
            ['id'=>264,'brand_id'=>33,'name'=>'Strakonice'],
            ['id'=>265,'brand_id'=>33,'name'=>'TS'],
            ['id'=>266,'brand_id'=>33,'name'=>'Otro Modelo'],
            ['id'=>267,'brand_id'=>34,'name'=>'JS'],
            ['id'=>268,'brand_id'=>34,'name'=>'Otro Modelo'],
            ['id'=>269,'brand_id'=>35,'name'=>'JC'],
            ['id'=>270,'brand_id'=>35,'name'=>'Otro Modelo'],
            ['id'=>271,'brand_id'=>36,'name'=>'5'],
            ['id'=>272,'brand_id'=>36,'name'=>'Otro Modelo'],
            ['id'=>273,'brand_id'=>37,'name'=>'Citycoco'],
            ['id'=>274,'brand_id'=>37,'name'=>'Súper Soco'],
            ['id'=>275,'brand_id'=>37,'name'=>'Sur Ron'],
            ['id'=>276,'brand_id'=>37,'name'=>'Otro Modelo'],
            ['id'=>277,'brand_id'=>38,'name'=>'AR'],
            ['id'=>278,'brand_id'=>38,'name'=>'Custom'],
            ['id'=>279,'brand_id'=>38,'name'=>'Cyclone'],
            ['id'=>280,'brand_id'=>38,'name'=>'Eliminator'],
            ['id'=>281,'brand_id'=>38,'name'=>'ER'],
            ['id'=>282,'brand_id'=>38,'name'=>'GPX'],
            ['id'=>283,'brand_id'=>38,'name'=>'GPZ'],
            ['id'=>284,'brand_id'=>38,'name'=>'GTO'],
            ['id'=>285,'brand_id'=>38,'name'=>'KDX'],
            ['id'=>286,'brand_id'=>38,'name'=>'KL'],
            ['id'=>287,'brand_id'=>38,'name'=>'KLE'],
            ['id'=>288,'brand_id'=>38,'name'=>'KLR'],
            ['id'=>289,'brand_id'=>38,'name'=>'KLX'],
            ['id'=>290,'brand_id'=>38,'name'=>'KMX'],
            ['id'=>291,'brand_id'=>38,'name'=>'KR'],
            ['id'=>292,'brand_id'=>38,'name'=>'KX'],
            ['id'=>293,'brand_id'=>38,'name'=>'KZ'],
            ['id'=>294,'brand_id'=>38,'name'=>'LTD'],
            ['id'=>295,'brand_id'=>38,'name'=>'Ninja'],
            ['id'=>296,'brand_id'=>38,'name'=>'SR'],
            ['id'=>297,'brand_id'=>38,'name'=>'Versys'],
            ['id'=>298,'brand_id'=>38,'name'=>'Voyager'],
            ['id'=>299,'brand_id'=>38,'name'=>'Vulcan'],
            ['id'=>300,'brand_id'=>38,'name'=>'W'],
            ['id'=>301,'brand_id'=>38,'name'=>'WR'],
            ['id'=>302,'brand_id'=>38,'name'=>'Z'],
            ['id'=>303,'brand_id'=>38,'name'=>'ZG'],
            ['id'=>304,'brand_id'=>38,'name'=>'ZR'],
            ['id'=>305,'brand_id'=>38,'name'=>'ZX'],
            ['id'=>306,'brand_id'=>38,'name'=>'ZZR'],
            ['id'=>307,'brand_id'=>38,'name'=>'Otro Modelo'],
            ['id'=>308,'brand_id'=>39,'name'=>'RKV'],
            ['id'=>309,'brand_id'=>39,'name'=>'Speed Cruiser'],
            ['id'=>310,'brand_id'=>39,'name'=>'Otro Modelo'],
            ['id'=>311,'brand_id'=>40,'name'=>'Big'],
            ['id'=>312,'brand_id'=>40,'name'=>'Champions'],
            ['id'=>313,'brand_id'=>40,'name'=>'Conquista'],
            ['id'=>314,'brand_id'=>40,'name'=>'Crono'],
            ['id'=>315,'brand_id'=>40,'name'=>'Excellence'],
            ['id'=>316,'brand_id'=>40,'name'=>'Exotic'],
            ['id'=>317,'brand_id'=>40,'name'=>'Jet-Max'],
            ['id'=>318,'brand_id'=>40,'name'=>'K'],
            ['id'=>319,'brand_id'=>40,'name'=>'K2'],
            ['id'=>320,'brand_id'=>40,'name'=>'KN'],
            ['id'=>321,'brand_id'=>40,'name'=>'KR'],
            ['id'=>322,'brand_id'=>40,'name'=>'Matrix'],
            ['id'=>323,'brand_id'=>40,'name'=>'Miracle'],
            ['id'=>324,'brand_id'=>40,'name'=>'MX'],
            ['id'=>325,'brand_id'=>40,'name'=>'Power'],
            ['id'=>326,'brand_id'=>40,'name'=>'Quasar'],
            ['id'=>327,'brand_id'=>40,'name'=>'Satelix'],
            ['id'=>328,'brand_id'=>40,'name'=>'Stratus'],
            ['id'=>329,'brand_id'=>40,'name'=>'Titan'],
            ['id'=>330,'brand_id'=>40,'name'=>'Tropical'],
            ['id'=>331,'brand_id'=>40,'name'=>'Xtreme'],
            ['id'=>332,'brand_id'=>40,'name'=>'Otro Modelo'],
            ['id'=>333,'brand_id'=>41,'name'=>'DK'],
            ['id'=>334,'brand_id'=>41,'name'=>'Otro Modelo'],
            ['id'=>335,'brand_id'=>42,'name'=>'Citizen'],
            ['id'=>336,'brand_id'=>42,'name'=>'Dakos'],
            ['id'=>337,'brand_id'=>42,'name'=>'Enduro'],
            ['id'=>338,'brand_id'=>42,'name'=>'Keoken'],
            ['id'=>339,'brand_id'=>42,'name'=>'LX'],
            ['id'=>340,'brand_id'=>42,'name'=>'Magnifika'],
            ['id'=>341,'brand_id'=>42,'name'=>'Tucubix'],
            ['id'=>342,'brand_id'=>42,'name'=>'Tucubiz'],
            ['id'=>343,'brand_id'=>42,'name'=>'Win-K'],
            ['id'=>344,'brand_id'=>42,'name'=>'Otro Modelo'],
            ['id'=>345,'brand_id'=>43,'name'=>'Adventure'],
            ['id'=>346,'brand_id'=>43,'name'=>'Duke'],
            ['id'=>347,'brand_id'=>43,'name'=>'Enduro'],
            ['id'=>348,'brand_id'=>43,'name'=>'Enduro Comp'],
            ['id'=>349,'brand_id'=>43,'name'=>'EXC'],
            ['id'=>350,'brand_id'=>43,'name'=>'Rally'],
            ['id'=>351,'brand_id'=>43,'name'=>'SM'],
            ['id'=>352,'brand_id'=>43,'name'=>'SMC'],
            ['id'=>353,'brand_id'=>43,'name'=>'SMT'],
            ['id'=>354,'brand_id'=>43,'name'=>'Super Duke'],
            ['id'=>355,'brand_id'=>43,'name'=>'SX'],
            ['id'=>356,'brand_id'=>43,'name'=>'SX-F'],
            ['id'=>357,'brand_id'=>43,'name'=>'Otro Modelo'],
            ['id'=>358,'brand_id'=>44,'name'=>'XF'],
            ['id'=>359,'brand_id'=>44,'name'=>'Otro Modelo'],
            ['id'=>360,'brand_id'=>45,'name'=>'Activ'],
            ['id'=>361,'brand_id'=>45,'name'=>'Agility'],
            ['id'=>362,'brand_id'=>45,'name'=>'AXR'],
            ['id'=>363,'brand_id'=>45,'name'=>'Bet y Win'],
            ['id'=>364,'brand_id'=>45,'name'=>'Cub'],
            ['id'=>365,'brand_id'=>45,'name'=>'Dink'],
            ['id'=>366,'brand_id'=>45,'name'=>'DJ'],
            ['id'=>367,'brand_id'=>45,'name'=>'Downtown'],
            ['id'=>368,'brand_id'=>45,'name'=>'Grand Dink'],
            ['id'=>369,'brand_id'=>45,'name'=>'Grand King'],
            ['id'=>370,'brand_id'=>45,'name'=>'Heroism'],
            ['id'=>371,'brand_id'=>45,'name'=>'Hipster'],
            ['id'=>372,'brand_id'=>45,'name'=>'KB'],
            ['id'=>373,'brand_id'=>45,'name'=>'Like'],
            ['id'=>374,'brand_id'=>45,'name'=>'Master'],
            ['id'=>375,'brand_id'=>45,'name'=>'People'],
            ['id'=>376,'brand_id'=>45,'name'=>'Plasure'],
            ['id'=>377,'brand_id'=>45,'name'=>'Pronto'],
            ['id'=>378,'brand_id'=>45,'name'=>'Pulsar'],
            ['id'=>379,'brand_id'=>45,'name'=>'Quannon'],
            ['id'=>380,'brand_id'=>45,'name'=>'Spike'],
            ['id'=>381,'brand_id'=>45,'name'=>'Stryker'],
            ['id'=>382,'brand_id'=>45,'name'=>'Super'],
            ['id'=>383,'brand_id'=>45,'name'=>'Top Boy'],
            ['id'=>384,'brand_id'=>45,'name'=>'Venox'],
            ['id'=>385,'brand_id'=>45,'name'=>'Visa'],
            ['id'=>386,'brand_id'=>45,'name'=>'Xciting'],
            ['id'=>387,'brand_id'=>45,'name'=>'Yup'],
            ['id'=>388,'brand_id'=>45,'name'=>'Zing'],
            ['id'=>389,'brand_id'=>45,'name'=>'ZX'],
            ['id'=>390,'brand_id'=>45,'name'=>'Otro Modelo'],
            ['id'=>391,'brand_id'=>46,'name'=>'LD'],
            ['id'=>392,'brand_id'=>46,'name'=>'Otro Modelo'],
            ['id'=>393,'brand_id'=>47,'name'=>'Capri'],
            ['id'=>394,'brand_id'=>47,'name'=>'Imola'],
            ['id'=>395,'brand_id'=>47,'name'=>'Milano'],
            ['id'=>396,'brand_id'=>47,'name'=>'Modena'],
            ['id'=>397,'brand_id'=>47,'name'=>'Monza'],
            ['id'=>398,'brand_id'=>47,'name'=>'Verona'],
            ['id'=>399,'brand_id'=>47,'name'=>'YG'],
            ['id'=>400,'brand_id'=>47,'name'=>'Otro Modelo'],
            ['id'=>401,'brand_id'=>48,'name'=>'Eléctrica'],
            ['id'=>402,'brand_id'=>48,'name'=>'Otro Modelo'],
            ['id'=>403,'brand_id'=>49,'name'=>'500'],
            ['id'=>404,'brand_id'=>49,'name'=>'Otro Modelo'],
            ['id'=>405,'brand_id'=>50,'name'=>'Black Star'],
            ['id'=>406,'brand_id'=>50,'name'=>'City'],
            ['id'=>407,'brand_id'=>50,'name'=>'Dual'],
            ['id'=>408,'brand_id'=>50,'name'=>'F1'],
            ['id'=>409,'brand_id'=>50,'name'=>'Fox'],
            ['id'=>410,'brand_id'=>50,'name'=>'Goldwing'],
            ['id'=>411,'brand_id'=>50,'name'=>'GY'],
            ['id'=>412,'brand_id'=>50,'name'=>'Halley'],
            ['id'=>413,'brand_id'=>50,'name'=>'Maxim'],
            ['id'=>414,'brand_id'=>50,'name'=>'Nexus'],
            ['id'=>415,'brand_id'=>50,'name'=>'Omega'],
            ['id'=>416,'brand_id'=>50,'name'=>'Panther'],
            ['id'=>417,'brand_id'=>50,'name'=>'Street'],
            ['id'=>418,'brand_id'=>50,'name'=>'Supra'],
            ['id'=>419,'brand_id'=>50,'name'=>'Terra'],
            ['id'=>420,'brand_id'=>50,'name'=>'Top'],
            ['id'=>421,'brand_id'=>50,'name'=>'Wind'],
            ['id'=>422,'brand_id'=>50,'name'=>'XRT'],
            ['id'=>423,'brand_id'=>50,'name'=>'Otro Modelo'],
            ['id'=>424,'brand_id'=>51,'name'=>'AX'],
            ['id'=>425,'brand_id'=>51,'name'=>'BD'],
            ['id'=>426,'brand_id'=>51,'name'=>'Dax'],
            ['id'=>427,'brand_id'=>51,'name'=>'EX'],
            ['id'=>428,'brand_id'=>51,'name'=>'Free'],
            ['id'=>429,'brand_id'=>51,'name'=>'HD'],
            ['id'=>430,'brand_id'=>51,'name'=>'KX'],
            ['id'=>431,'brand_id'=>51,'name'=>'LD'],
            ['id'=>432,'brand_id'=>51,'name'=>'MD'],
            ['id'=>433,'brand_id'=>51,'name'=>'MS'],
            ['id'=>434,'brand_id'=>51,'name'=>'QJ'],
            ['id'=>435,'brand_id'=>51,'name'=>'RD'],
            ['id'=>436,'brand_id'=>51,'name'=>'RV'],
            ['id'=>437,'brand_id'=>51,'name'=>'Scarabeo'],
            ['id'=>438,'brand_id'=>51,'name'=>'TD'],
            ['id'=>439,'brand_id'=>51,'name'=>'VD'],
            ['id'=>440,'brand_id'=>51,'name'=>'Otro Modelo'],
            ['id'=>441,'brand_id'=>52,'name'=>'Beverly Cruiser'],
            ['id'=>442,'brand_id'=>52,'name'=>'Bit'],
            ['id'=>443,'brand_id'=>52,'name'=>'Blitz'],
            ['id'=>444,'brand_id'=>52,'name'=>'C110'],
            ['id'=>445,'brand_id'=>52,'name'=>'Calle'],
            ['id'=>446,'brand_id'=>52,'name'=>'CG'],
            ['id'=>447,'brand_id'=>52,'name'=>'Clipper'],
            ['id'=>448,'brand_id'=>52,'name'=>'Custom'],
            ['id'=>449,'brand_id'=>52,'name'=>'Dakar'],
            ['id'=>450,'brand_id'=>52,'name'=>'DLX'],
            ['id'=>451,'brand_id'=>52,'name'=>'Dream'],
            ['id'=>452,'brand_id'=>52,'name'=>'Eco'],
            ['id'=>453,'brand_id'=>52,'name'=>'Forza'],
            ['id'=>454,'brand_id'=>52,'name'=>'Function'],
            ['id'=>455,'brand_id'=>52,'name'=>'Fusion'],
            ['id'=>456,'brand_id'=>52,'name'=>'Go'],
            ['id'=>457,'brand_id'=>52,'name'=>'Hero Puch'],
            ['id'=>458,'brand_id'=>52,'name'=>'Hyosung'],
            ['id'=>459,'brand_id'=>52,'name'=>'Max'],
            ['id'=>460,'brand_id'=>52,'name'=>'Medal'],
            ['id'=>461,'brand_id'=>52,'name'=>'Megelli'],
            ['id'=>462,'brand_id'=>52,'name'=>'Milestone'],
            ['id'=>463,'brand_id'=>52,'name'=>'Motard'],
            ['id'=>464,'brand_id'=>52,'name'=>'Motocargo'],
            ['id'=>465,'brand_id'=>52,'name'=>'PX'],
            ['id'=>466,'brand_id'=>52,'name'=>'Rider'],
            ['id'=>467,'brand_id'=>52,'name'=>'S6'],
            ['id'=>468,'brand_id'=>52,'name'=>'Sirius'],
            ['id'=>469,'brand_id'=>52,'name'=>'Skorpion'],
            ['id'=>470,'brand_id'=>52,'name'=>'Skua'],
            ['id'=>471,'brand_id'=>52,'name'=>'SL'],
            ['id'=>472,'brand_id'=>52,'name'=>'Speedy'],
            ['id'=>473,'brand_id'=>52,'name'=>'SR'],
            ['id'=>474,'brand_id'=>52,'name'=>'Strato'],
            ['id'=>475,'brand_id'=>52,'name'=>'TCP'],
            ['id'=>476,'brand_id'=>52,'name'=>'Top'],
            ['id'=>477,'brand_id'=>52,'name'=>'Tricargo'],
            ['id'=>478,'brand_id'=>52,'name'=>'Triciclo'],
            ['id'=>479,'brand_id'=>52,'name'=>'Vespa'],
            ['id'=>480,'brand_id'=>52,'name'=>'VX'],
            ['id'=>481,'brand_id'=>52,'name'=>'Wasp'],
            ['id'=>482,'brand_id'=>52,'name'=>'X3M'],
            ['id'=>483,'brand_id'=>52,'name'=>'X-Evo'],
            ['id'=>484,'brand_id'=>52,'name'=>'XMM'],
            ['id'=>485,'brand_id'=>52,'name'=>'Xplora'],
            ['id'=>486,'brand_id'=>52,'name'=>'Otro Modelo'],
            ['id'=>487,'brand_id'=>53,'name'=>'110'],
            ['id'=>488,'brand_id'=>53,'name'=>'125'],
            ['id'=>489,'brand_id'=>53,'name'=>'150'],
            ['id'=>490,'brand_id'=>53,'name'=>'R125'],
            ['id'=>491,'brand_id'=>53,'name'=>'R150'],
            ['id'=>492,'brand_id'=>53,'name'=>'R250'],
            ['id'=>493,'brand_id'=>53,'name'=>'ST'],
            ['id'=>494,'brand_id'=>53,'name'=>'Otro Modelo'],
            ['id'=>495,'brand_id'=>54,'name'=>'Lusso Veloce'],
            ['id'=>496,'brand_id'=>54,'name'=>'Otro Modelo'],
            ['id'=>497,'brand_id'=>55,'name'=>'Zenith'],
            ['id'=>498,'brand_id'=>55,'name'=>'Otro Modelo'],
            ['id'=>499,'brand_id'=>56,'name'=>'Vento'],
            ['id'=>500,'brand_id'=>56,'name'=>'Otro Modelo'],
            ['id'=>501,'brand_id'=>57,'name'=>'Beverly'],
            ['id'=>502,'brand_id'=>57,'name'=>'Hexagon'],
            ['id'=>503,'brand_id'=>57,'name'=>'Vespa'],
            ['id'=>504,'brand_id'=>57,'name'=>'Otro Modelo'],
            ['id'=>505,'brand_id'=>58,'name'=>'125'],
            ['id'=>506,'brand_id'=>58,'name'=>'200'],
            ['id'=>507,'brand_id'=>58,'name'=>'98'],
            ['id'=>508,'brand_id'=>58,'name'=>'Otro Modelo'],
            ['id'=>509,'brand_id'=>59,'name'=>'Bullet'],
            ['id'=>510,'brand_id'=>59,'name'=>'Electra'],
            ['id'=>511,'brand_id'=>59,'name'=>'Otro Modelo'],
            ['id'=>512,'brand_id'=>60,'name'=>'SEF-R'],
            ['id'=>513,'brand_id'=>60,'name'=>'SE-R'],
            ['id'=>514,'brand_id'=>60,'name'=>'Otro Modelo'],
            ['id'=>515,'brand_id'=>61,'name'=>'AV'],
            ['id'=>516,'brand_id'=>61,'name'=>'Innocenti'],
            ['id'=>517,'brand_id'=>61,'name'=>'LD'],
            ['id'=>518,'brand_id'=>61,'name'=>'Standard'],
            ['id'=>519,'brand_id'=>61,'name'=>'TV'],
            ['id'=>520,'brand_id'=>61,'name'=>'Otro Modelo'],
            ['id'=>521,'brand_id'=>62,'name'=>'SL'],
            ['id'=>522,'brand_id'=>62,'name'=>'SP'],
            ['id'=>523,'brand_id'=>62,'name'=>'Otro Modelo'],
            ['id'=>524,'brand_id'=>63,'name'=>'Hobiz'],
            ['id'=>525,'brand_id'=>63,'name'=>'Rapid'],
            ['id'=>526,'brand_id'=>63,'name'=>'SG'],
            ['id'=>527,'brand_id'=>63,'name'=>'SL'],
            ['id'=>528,'brand_id'=>63,'name'=>'Otro Modelo'],
            ['id'=>529,'brand_id'=>64,'name'=>'Eco Winco'],
            ['id'=>530,'brand_id'=>64,'name'=>'Grace'],
            ['id'=>531,'brand_id'=>64,'name'=>'Hawk'],
            ['id'=>532,'brand_id'=>64,'name'=>'King Kong'],
            ['id'=>533,'brand_id'=>64,'name'=>'Panther'],
            ['id'=>534,'brand_id'=>64,'name'=>'Shino'],
            ['id'=>535,'brand_id'=>64,'name'=>'Shinox'],
            ['id'=>536,'brand_id'=>64,'name'=>'Spyracing'],
            ['id'=>537,'brand_id'=>64,'name'=>'Vintage Vespa'],
            ['id'=>538,'brand_id'=>64,'name'=>'Otro Modelo'],
            ['id'=>539,'brand_id'=>65,'name'=>'AN'],
            ['id'=>540,'brand_id'=>65,'name'=>'AX'],
            ['id'=>541,'brand_id'=>65,'name'=>'Bandit'],
            ['id'=>542,'brand_id'=>65,'name'=>'Boulevard'],
            ['id'=>543,'brand_id'=>65,'name'=>'DR'],
            ['id'=>544,'brand_id'=>65,'name'=>'DRZ'],
            ['id'=>545,'brand_id'=>65,'name'=>'DS'],
            ['id'=>546,'brand_id'=>65,'name'=>'EN125'],
            ['id'=>547,'brand_id'=>65,'name'=>'FXR'],
            ['id'=>548,'brand_id'=>65,'name'=>'GN125'],
            ['id'=>549,'brand_id'=>65,'name'=>'GS'],
            ['id'=>550,'brand_id'=>65,'name'=>'GSR'],
            ['id'=>551,'brand_id'=>65,'name'=>'GSX'],
            ['id'=>552,'brand_id'=>65,'name'=>'GSXR'],
            ['id'=>553,'brand_id'=>65,'name'=>'Inazuma'],
            ['id'=>554,'brand_id'=>65,'name'=>'Marauder'],
            ['id'=>555,'brand_id'=>65,'name'=>'RG'],
            ['id'=>556,'brand_id'=>65,'name'=>'RGV'],
            ['id'=>557,'brand_id'=>65,'name'=>'RM'],
            ['id'=>558,'brand_id'=>65,'name'=>'RMZ'],
            ['id'=>559,'brand_id'=>65,'name'=>'RV'],
            ['id'=>560,'brand_id'=>65,'name'=>'Savage'],
            ['id'=>561,'brand_id'=>65,'name'=>'SJ'],
            ['id'=>562,'brand_id'=>65,'name'=>'SV'],
            ['id'=>563,'brand_id'=>65,'name'=>'TS'],
            ['id'=>564,'brand_id'=>65,'name'=>'VL'],
            ['id'=>565,'brand_id'=>65,'name'=>'V-Strom'],
            ['id'=>566,'brand_id'=>65,'name'=>'Otro Modelo'],
            ['id'=>567,'brand_id'=>66,'name'=>'Gran Milano'],
            ['id'=>568,'brand_id'=>66,'name'=>'Rs'],
            ['id'=>569,'brand_id'=>66,'name'=>'Super Dual'],
            ['id'=>570,'brand_id'=>66,'name'=>'Otro Modelo'],
            ['id'=>571,'brand_id'=>67,'name'=>'Fiddle II'],
            ['id'=>572,'brand_id'=>67,'name'=>'Otro Modelo'],
            ['id'=>573,'brand_id'=>68,'name'=>'RF'],
            ['id'=>574,'brand_id'=>68,'name'=>'Otro Modelo'],
            ['id'=>575,'brand_id'=>69,'name'=>'Coaster'],
            ['id'=>576,'brand_id'=>69,'name'=>'Otro Modelo'],
            ['id'=>577,'brand_id'=>70,'name'=>'America'],
            ['id'=>578,'brand_id'=>70,'name'=>'Bonneville'],
            ['id'=>579,'brand_id'=>70,'name'=>'Rocket III'],
            ['id'=>580,'brand_id'=>70,'name'=>'Speed Twin'],
            ['id'=>581,'brand_id'=>70,'name'=>'Otro Modelo'],
            ['id'=>582,'brand_id'=>71,'name'=>'U mini'],
            ['id'=>583,'brand_id'=>71,'name'=>'U1'],
            ['id'=>584,'brand_id'=>71,'name'=>'Otro Modelo'],
            ['id'=>585,'brand_id'=>72,'name'=>'Avalon'],
            ['id'=>586,'brand_id'=>72,'name'=>'Otro Modelo'],
            ['id'=>587,'brand_id'=>73,'name'=>'Axis'],
            ['id'=>588,'brand_id'=>73,'name'=>'Crypton'],
            ['id'=>589,'brand_id'=>73,'name'=>'Cygnus'],
            ['id'=>590,'brand_id'=>73,'name'=>'Dragstar'],
            ['id'=>591,'brand_id'=>73,'name'=>'DT'],
            ['id'=>592,'brand_id'=>73,'name'=>'Fazer'],
            ['id'=>593,'brand_id'=>73,'name'=>'FJR'],
            ['id'=>594,'brand_id'=>73,'name'=>'FZ'],
            ['id'=>595,'brand_id'=>73,'name'=>'FZR'],
            ['id'=>596,'brand_id'=>73,'name'=>'FZ-S'],
            ['id'=>597,'brand_id'=>73,'name'=>'Jog'],
            ['id'=>598,'brand_id'=>73,'name'=>'MT'],
            ['id'=>599,'brand_id'=>73,'name'=>'New Crypton'],
            ['id'=>600,'brand_id'=>73,'name'=>'NM-X'],
            ['id'=>601,'brand_id'=>73,'name'=>'PW'],
            ['id'=>602,'brand_id'=>73,'name'=>'R'],
            ['id'=>603,'brand_id'=>73,'name'=>'R1'],
            ['id'=>604,'brand_id'=>73,'name'=>'R6'],
            ['id'=>605,'brand_id'=>73,'name'=>'Raaz'],
            ['id'=>606,'brand_id'=>73,'name'=>'Radian'],
            ['id'=>607,'brand_id'=>73,'name'=>'RD'],
            ['id'=>608,'brand_id'=>73,'name'=>'RXZ'],
            ['id'=>609,'brand_id'=>73,'name'=>'RZ'],
            ['id'=>610,'brand_id'=>73,'name'=>'Serow'],
            ['id'=>611,'brand_id'=>73,'name'=>'Sigma'],
            ['id'=>612,'brand_id'=>73,'name'=>'SZ-RR'],
            ['id'=>613,'brand_id'=>73,'name'=>'TDM'],
            ['id'=>614,'brand_id'=>73,'name'=>'TTR'],
            ['id'=>615,'brand_id'=>73,'name'=>'TW'],
            ['id'=>616,'brand_id'=>73,'name'=>'V'],
            ['id'=>617,'brand_id'=>73,'name'=>'Virago'],
            ['id'=>618,'brand_id'=>73,'name'=>'V-Max'],
            ['id'=>619,'brand_id'=>73,'name'=>'VRR'],
            ['id'=>620,'brand_id'=>73,'name'=>'V-Star'],
            ['id'=>621,'brand_id'=>73,'name'=>'WR'],
            ['id'=>622,'brand_id'=>73,'name'=>'WRF'],
            ['id'=>623,'brand_id'=>73,'name'=>'XJ'],
            ['id'=>624,'brand_id'=>73,'name'=>'XJR'],
            ['id'=>625,'brand_id'=>73,'name'=>'XP'],
            ['id'=>626,'brand_id'=>73,'name'=>'XS'],
            ['id'=>627,'brand_id'=>73,'name'=>'XT'],
            ['id'=>628,'brand_id'=>73,'name'=>'XTZ'],
            ['id'=>629,'brand_id'=>73,'name'=>'XV'],
            ['id'=>630,'brand_id'=>73,'name'=>'XVS'],
            ['id'=>631,'brand_id'=>73,'name'=>'YBR'],
            ['id'=>632,'brand_id'=>73,'name'=>'YP'],
            ['id'=>633,'brand_id'=>73,'name'=>'YS'],
            ['id'=>634,'brand_id'=>73,'name'=>'YZ'],
            ['id'=>635,'brand_id'=>73,'name'=>'YZF'],
            ['id'=>636,'brand_id'=>73,'name'=>'Otro Modelo'],
            ['id'=>637,'brand_id'=>74,'name'=>'Ceccato'],
            ['id'=>638,'brand_id'=>74,'name'=>'Chopera'],
            ['id'=>639,'brand_id'=>74,'name'=>'Crazy'],
            ['id'=>640,'brand_id'=>74,'name'=>'Custom'],
            ['id'=>641,'brand_id'=>74,'name'=>'Delivery'],
            ['id'=>642,'brand_id'=>74,'name'=>'Due'],
            ['id'=>643,'brand_id'=>74,'name'=>'Goldfish'],
            ['id'=>644,'brand_id'=>74,'name'=>'Gran Turismo'],
            ['id'=>645,'brand_id'=>74,'name'=>'HJ'],
            ['id'=>646,'brand_id'=>74,'name'=>'Hot'],
            ['id'=>647,'brand_id'=>74,'name'=>'JR'],
            ['id'=>648,'brand_id'=>74,'name'=>'Keeway'],
            ['id'=>649,'brand_id'=>74,'name'=>'Lambretta'],
            ['id'=>650,'brand_id'=>74,'name'=>'Mod'],
            ['id'=>651,'brand_id'=>74,'name'=>'Monaco'],
            ['id'=>652,'brand_id'=>74,'name'=>'New Fire'],
            ['id'=>653,'brand_id'=>74,'name'=>'NT'],
            ['id'=>654,'brand_id'=>74,'name'=>'Patagonia'],
            ['id'=>655,'brand_id'=>74,'name'=>'Patagonian Eagle'],
            ['id'=>656,'brand_id'=>74,'name'=>'Pocket'],
            ['id'=>657,'brand_id'=>74,'name'=>'Rally'],
            ['id'=>658,'brand_id'=>74,'name'=>'Raptor'],
            ['id'=>659,'brand_id'=>74,'name'=>'RX'],
            ['id'=>660,'brand_id'=>74,'name'=>'RZ'],
            ['id'=>661,'brand_id'=>74,'name'=>'Sapucai'],
            ['id'=>662,'brand_id'=>74,'name'=>'Sexy'],
            ['id'=>663,'brand_id'=>74,'name'=>'Sol'],
            ['id'=>664,'brand_id'=>74,'name'=>'Street'],
            ['id'=>665,'brand_id'=>74,'name'=>'Styler'],
            ['id'=>666,'brand_id'=>74,'name'=>'Swing'],
            ['id'=>667,'brand_id'=>74,'name'=>'Techbikes'],
            ['id'=>668,'brand_id'=>74,'name'=>'Tricargo'],
            ['id'=>669,'brand_id'=>74,'name'=>'TX'],
            ['id'=>670,'brand_id'=>74,'name'=>'Vento'],
            ['id'=>671,'brand_id'=>74,'name'=>'ZB'],
            ['id'=>672,'brand_id'=>74,'name'=>'Z-Cap'],
            ['id'=>673,'brand_id'=>74,'name'=>'Z-Max'],
            ['id'=>674,'brand_id'=>74,'name'=>'ZR'],
            ['id'=>675,'brand_id'=>74,'name'=>'Z-Truck'],
            ['id'=>676,'brand_id'=>74,'name'=>'ZTT'],
            ['id'=>677,'brand_id'=>74,'name'=>'Otro Modelo'],
        ];

        foreach ($patterns as $pattern) {
            \App\Pattern::create($pattern);
        }
    }
}
